#!/bin/bash

# what to optimise
sector="45"
z0="-217000"
rps="3,4,5,23,24,25"

# planes 4.4, 23.5
# excludePlanes="1981939712,2023555072"
# planes 4.4, (003.5, 23.2 & 23.4 in 2023 pixels only)
# add planes 024.0-024.3
excludePlanes="1981939712,2015166464,2023358464,2023489536,1990197248,1990230016,1990262784,1990295552"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
#maxEvents="-1" # process all events
maxEvents="4E5"

# iteration settings
iterations=5
optimize=("s" "s" "sr")
iterationsWithOneRotZPerPot=0
maxResidualToSigma=(30 10 10 5 3)
chiSqPerNdfCut=(500 50 50 15 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard"
constraintsLabel="std"
final_constraints_units="1,21"
useEqualMeanUMeanVRotZConstraints="True"

# diagonistics
iterationsWithDiagnostics="5"

# input settings
reco_dir="/ZeroBias1/Run2023C-PromptReco-v4/AOD run=369596"
# no offsets
horizontalOffsets="'3:-0.572', '23:-1.030'"

# geometry settings
geometry="CalibPPS/AlignmentRelative/test/test_with_data"

initial_alignment=()

# output settings
subdir="data"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	369596.0-40
	# 324579.26-50
	# 324579.51-75
	# 324579.76-99
)

SubmitTrackBasedAlignment
