#!/bin/bash

# what to optimise
sector="56"
z0="+217000"
rps="103,104,105,123,124,125"

# 124.8, 124.9
excludePlanes="2007236608,2007269376"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
# maxEvents="-1" # process all events
maxEvents="1E4"

# iteration settings
iterations=5
optimize=("s" "s" "sr")
iterationsWithOneRotZPerPot=0
maxResidualToSigma=(30 10 10 3)
chiSqPerNdfCut=(500 50 50 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard"
constraintsLabel="std"
final_constraints_units="101,121"
useEqualMeanUMeanVRotZConstraints="True"

# diagonistics
iterationsWithDiagnostics="5"

# input settings
reco_dir="/eos/user/j/jaczajka/documents/datasets/zeroBias2023_v3"
horizontalOffsets="'103:1.295', '123:2.179'"
# horizontalOffsets=""

# geometry settings
geometry="CalibPPS/AlignmentRelative/run/Zero_bias_2023_V2"

initial_alignment=()

# output settings
subdir="data"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	369591.0-200
)

SubmitTrackBasedAlignment
