#!/bin/bash

# what to optimise
sector="56"
z0="+217000"
rps="103,104,105,123,124,125"

# 124.8, 124.9
excludePlanes="2007236608,2007269376"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
# maxEvents="-1" # process all events
maxEvents="4E5"

# iteration settings
iterations=5
optimize=("s" "s" "sr")
iterationsWithOneRotZPerPot=0
maxResidualToSigma=(30 10 10 5 3)
chiSqPerNdfCut=(500 50 50 15 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard"
constraintsLabel="std"
final_constraints_units="101,121"
useEqualMeanUMeanVRotZConstraints="True"

# diagonistics
iterationsWithDiagnostics="5"

# input settings
reco_dir="/ZeroBias1/Run2023C-PromptReco-v4/AOD run=369596"
horizontalOffsets="'103:-0.564', '123:-0.293'"
# horizontalOffsets=""

# geometry settings
geometry="CalibPPS/AlignmentRelative/test/test_with_data"

initial_alignment=()

# output settings
subdir="data"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	369596.0-40
)

SubmitTrackBasedAlignment
